# Generated by Django 6.0 on 2025-12-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='matric_number',
        ),
    ]
